export * as CategoryApi from "./categoryApi";
export * as FriendRequestApi from "./friend-request";
export * as FriendsApi from "./friends";
export * as ScheduledSessionApi from "./scheduledSessionApi";
export * as StatisticsApi from "./statisticsApi";
export * as StopwatchApi from "./stopwatchApi";
export * as TagApi from "./tagApi";
export * as SessionTemplateApi from "./templateApi";
export * as UserApi from "./userApi";
