name: Rust Linting with Clippy

on:
  push:
    paths:
      - "backend/**"
  pull_request:
    paths:
      - "backend/**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for backend changes
        id: changes
        run: |
          echo "Checking for changes in backend..."
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^backend/'; then
            echo "backend_changed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes in backend directory."
            echo "backend_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Install Rust
        if: steps.changes.outputs.backend_changed == 'true'
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy

      - name: Run Clippy
        if: steps.changes.outputs.backend_changed == 'true'
        working-directory: backend
        run: cargo clippy -- -D warnings -A unused

      - name: Run Rustfmt
        if: steps.changes.outputs.backend_changed == 'true'
        working-directory: backend
        run: cargo fmt -- --check
